#
# Module manifest for module 'VeriHash.HotPath'
#
# Generated by: arcticpinecone
#
# Generated on: 2026-04-18
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'VeriHash.HotPath.psm1'

# Version number of this module.
ModuleVersion = '2.0.0'

# Supported PSEditions
CompatiblePSEditions = 'Core'

# ID used to uniquely identify this module
GUID = '23dd5e06-ffed-420a-92fb-488cb9087ccc'

# Author of this module
Author = 'arcticpinecone'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) arcticpinecone. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Hot-path orchestration: PE-detect, parallel hash+Authenticode, multi-file batch with tally.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.0'

# Functions to export from this module
FunctionsToExport = 'Get-VeriHashSignature', 'Invoke-VeriHashHotPath', 'Invoke-VeriHashBatch'

# Format file for custom type display (VeriHash.HotPathResult, VeriHash.BatchResult)
FormatsToProcess = @('VeriHash.HotPath.format.ps1xml')

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

PrivateData = @{
    PSData = @{
    }
}

}
