#
# Module manifest for module 'VeriHash.Manifest'
#
# Generated by: arcticpinecone
#
# Generated on: 2026-04-19
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'VeriHash.Manifest.psm1'

# Version number of this module.
ModuleVersion = '3.0.0'

# Supported PSEditions
CompatiblePSEditions = 'Core'

# ID used to uniquely identify this module
GUID = '6d44d408-4617-479f-b8d4-39e5bd4c198f'

# Author of this module
Author = 'arcticpinecone'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) arcticpinecone. All rights reserved.'

# Description of the functionality provided by this module
Description = 'GNU sha256sum-compatible manifest creation and verification for VeriHash.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.0'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('VeriHash.Core')

# Functions to export from this module
FunctionsToExport = 'New-VeriHashManifest', 'Test-VeriHashManifest'

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

PrivateData = @{
    PSData = @{
    }
}

}
